# Generated by Django 4.2.4 on 2023-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='img',
            field=models.ImageField(upload_to='all_images'),
        ),
    ]
